siteTitle = "SPFx Samples"
title = "SPFx Samples"
baseURL = "https://pnp.github.io/sp-dev-fx-webparts/"
canonifyURLs = true
languageCode = "en-us"
theme = "pnp-hugo-theme"
publishDir = "docs"


[params]
description = "Learn from others how to build apps on Microsoft 365 & Power Platform."
callToAction = "Changing the world one contribution at a time!"
tagline = "<p>Learn from others how to build apps on Microsoft 365 & Power Platform.</p><p>Don't reinvent the wheel. Focus on what truly matters for your organization.</p>"
smallLogo = [ "SharePoint Framework", "(SPFx) Samples"]
disablePnPTelemetry = false
logo = "pnp.svg"
alternateName = "PnP"
noparker = true
customCSS =  ["css/custom.css"]

[[menus.main]]
identifier = "samples"
name = "Samples"
url = "/"
weight = 20

[[menus.main]]
identifier = "gettingstarted"
name = "Getting started"
url = "/gettingstarted/"
weight = 30

[[menus.main]]
identifier = "contributing"
name = "Contributing"
url = "/contributing"
weight = 40

[[params.bigLogo]]
line = "SharePoint Framework"

[[params.bigLogo]]
line = "(SPFx) Samples"
class = "fa-pp"

[params.clarity]
trackingCode = "a7tyzwydh7"

[[params.social]]
name = "GitHub"
icon = "icon-github"
weight = 1
url = "https://github.com/PnP/sp-dev-fx-webparts"

[[params.social]]
name = "Discord"
icon = "icon-discord"
weight = 5
url = "https://discord.com/channels/1095788595010338956/1096363629680529418"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params.pnpSamplesGallery]
 # Where to the data (relative to site base URL)
  dataSrc = "/sp-dev-fx-webparts/data/all-samples.json"

  # Reactions configuration for pnp-samples-gallery
  [params.pnpSamplesGallery.reactions]
    repo = "pnp/sp-dev-fx-webparts"
    repoId = "MDEwOlJlcG9zaXRvcnk2Njk2MjE3OQ=="
    category = "Likes"
    categoryId = "DIC_kwDOA_3DA84C0m26"
    likesFeed = "/sp-dev-fx-webparts/data/likes.json"
    enabled = true

  # Filters configuration: declare filter groups used by the gallery UI
  [params.pnpSamplesGallery.filters]
    # Each group is declared using the [[params.pnpSamplesGallery.filters.group]] table
    [[params.pnpSamplesGallery.filters.group]]
    key = "framework"
    label = "Framework"
    jsonPath = ["metadata","CLIENT-SIDE-DEV"]
    multiple = false
    values = [ { value = "React", label = "React" }, { value = "NoFramework", label = "No framework" } ]

    [[params.pnpSamplesGallery.filters.group]]
    key = "type"
    label = "Type"
    jsonPath = "metadata.SAMPLE-TYPE"
    multiple = false
    values = [ { value = "SPFx-WebPart", label = "Web Part" }, { value = "SPFx-Extension", label = "Extension" } ]