blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    about: ğŸ—¨ Start a friendly conversation with the other members of the community about the samples in this repository.
    url: https://github.com/pnp/sp-dev-fx-webparts/discussions
  - name: SharePoint Developer Documentation
    url: https://github.com/SharePoint/sp-dev-docs/issues/new
    about: ğŸ“š Issue related to the SharePoint Framework or its documentation? Submit an issue here.
  - name: SharePoint StackExchange
    url: http://sharepoint.stackexchange.com/
    about: â‰ï¸ If you have technical questions about the framework, tag your questions with `#spfx`, `#spfx-webparts`, or `#spfx-tooling` here.
  - name: Microsoft Tech Community
    url: https://techcommunity.microsoft.com/t5/sharepoint-developer/bd-p/SharePointDev
    about: â‰ï¸ Alternatively, submit your technical questions about the framework in the SharePoint Developer group here
